services:
  # db:
  #   container_name: card-meet--db
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile.prod
  #   env_file:
  #     - ./mysql/.env
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "7772:3306"
  #   networks:
  #     - card_meet_network


  # phpmyadmin:
  #   container_name: card-meet--phpmyadmin
  #   image: phpmyadmin:latest
  #   ports:
  #     - "7773:80"
  #   networks:
  #     - card_meet_network

  next:
    container_name: cm_fb--frontend
    build:
      context: ./next
      dockerfile: Dockerfile.prod
    ports:
      - "7770:3000"
    networks:
      - cm_fb_network

  fastapi:
    container_name: cm_fb--backend
    build:
      context: ./fastapi
      dockerfile: Dockerfile.prod
    ports:
      - "7771:8000"
    # depends_on:
    #   - db
    networks:
      - cm_fb_network
    environment:
      PYTHONPATH: /app

volumes:
  mysql_data:

networks:
  cm_fb_network:
    external: true